[project]
name = "predicta"
description = "Decentralized prediction markets on Stacks"
authors = []
telemetry = false

[contracts.predicta-core]
path = "contracts/predicta-core.clar"

[contracts.predicta-oracle]
path = "contracts/predicta-oracle.clar"

[contracts.predicta-resolution]
path = "contracts/predicta-resolution.clar"

[contracts.predicta-nfts]
path = "contracts/predicta-nfts.clar"
